name: Pull request requirements

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  check-linked-experiment:
    runs-on: ubuntu-latest
    steps:        
     - run: pip install ghapi
     - shell: python
       run: |
        import os
        from ghapi.core import GhApi
        owner, repo = os.environ['REPO'].split('/')
        api = GhApi(owner=owner, repo=repo)
        pull = api.pulls.get(os.environ['PR_NUMBER'])
        labels = [l.name for l in pull.labels]
        if 'new-run' in labels:
            assert 'experiment-linked' in labels, "The PR does not have the required label 'experiment-linked'. You can use the `/wandb <run_id>` command in a comment to link an experiment and add the label automatically."
       env:
        PR_NUMBER: ${{ github.event.number }} 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}